# Cloudflare Pages â€” Queens & Gods
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "queens-gods"
pages_build_output_dir = "."
compatibility_date = "2025-02-08"
compatibility_flags = ["nodejs_compat_v2"]
